basePath: /
definitions:
  handler.reportComment:
    properties:
      comment_id:
        type: integer
      reason:
        type: string
      user_id:
        type: integer
    required:
    - comment_id
    - reason
    - user_id
    type: object
  handler.reportPost:
    properties:
      post_id:
        type: integer
      reason:
        type: string
      user_id:
        type: integer
    required:
    - post_id
    - reason
    - user_id
    type: object
host: localhost:3000
info:
  contact: {}
  description: This a documentation for vescar challenge the objective is to provide
    an API to report comments and posts.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Vascar Challenge
  version: "1.0"
paths:
  /reports/comments:
    post:
      consumes:
      - application/json
      parameters:
      - description: report a comment
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/handler.reportComment'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create a report for a comment
      tags:
      - comments
  /reports/posts:
    post:
      consumes:
      - application/json
      parameters:
      - description: report a post
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/handler.reportPost'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create a report for a post
      tags:
      - posts
schemes:
- http
swagger: "2.0"
